config/routes.rb
Rails.application.routes.draw do
  devise_for :kitchen_owners
  devise_for :cooks
  root "kitchens#index"
  resources :kitchens
  resources :reservations
  resources :cooks
  resources :kitchen_owners
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/kitchen_owner.rb
class KitchenOwner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :reservations
end

app/controllers/kitchen_owners_controller.rb
class KitchenOwnersController < ApplicationController
  before_action :set_kitchen_owner, only: %i[ show edit update destroy ]

  # GET /kitchen_owners or /kitchen_owners.json
  def index
    @kitchen_owners = KitchenOwner.all
  end

  # GET /kitchen_owners/1 or /kitchen_owners/1.json
  def show
  end

  # GET /kitchen_owners/new
  def new
    @kitchen_owner = KitchenOwner.new
  end

  # GET /kitchen_owners/1/edit
  def edit
  end

  # POST /kitchen_owners or /kitchen_owners.json
  def create
    @kitchen_owner = KitchenOwner.new(kitchen_owner_params)

    respond_to do |format|
      if @kitchen_owner.save
        format.html { redirect_to kitchen_owner_url(@kitchen_owner), notice: "Kitchen owner was successfully created." }
        format.json { render :show, status: :created, location: @kitchen_owner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kitchen_owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kitchen_owners/1 or /kitchen_owners/1.json
  def update
    respond_to do |format|
      if @kitchen_owner.update(kitchen_owner_params)
        format.html { redirect_to kitchen_owner_url(@kitchen_owner), notice: "Kitchen owner was successfully updated." }
        format.json { render :show, status: :ok, location: @kitchen_owner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kitchen_owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitchen_owners/1 or /kitchen_owners/1.json
  def destroy
    @kitchen_owner.destroy

    respond_to do |format|
      format.html { redirect_to kitchen_owners_url, notice: "Kitchen owner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitchen_owner
      @kitchen_owner = KitchenOwner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kitchen_owner_params
      params.require(:kitchen_owner).permit(:kitchen_name, :string, :kitchen_mail, :kitchen_number, :kitchen_adress)
    end
end

app/helpers/kitchen_owners_helper.rb
module KitchenOwnersHelper
end

app/views/kitchen_owners/_form.html.erb
<%= form_with(model: kitchen_owner) do |form| %>
  <% if kitchen_owner.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kitchen_owner.errors.count, "error") %> prohibited this kitchen_owner from being saved:</h2>

      <ul>
        <% kitchen_owner.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :kitchen_name, style: "display: block" %>
    <%= form.text_field :kitchen_name %>
  </div>

  <div>
    <%= form.label :string, style: "display: block" %>
    <%= form.text_field :string %>
  </div>

  <div>
    <%= form.label :kitchen_mail, style: "display: block" %>
    <%= form.text_field :kitchen_mail %>
  </div>

  <div>
    <%= form.label :kitchen_number, style: "display: block" %>
    <%= form.number_field :kitchen_number %>
  </div>

  <div>
    <%= form.label :kitchen_adress, style: "display: block" %>
    <%= form.text_field :kitchen_adress %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kitchen_owners/_kitchen_owner.html.erb
<div id="<%= dom_id kitchen_owner %>">
  <p>
    <strong>Kitchen name:</strong>
    <%= kitchen_owner.kitchen_name %>
  </p>

  <p>
    <strong>String:</strong>
    <%= kitchen_owner.string %>
  </p>

  <p>
    <strong>Kitchen mail:</strong>
    <%= kitchen_owner.kitchen_mail %>
  </p>

  <p>
    <strong>Kitchen number:</strong>
    <%= kitchen_owner.kitchen_number %>
  </p>

  <p>
    <strong>Kitchen adress:</strong>
    <%= kitchen_owner.kitchen_adress %>
  </p>

</div>

app/views/kitchen_owners/edit.html.erb
<h1>Editing kitchen owner</h1>

<%= render "form", kitchen_owner: @kitchen_owner %>

<br>

<div>
  <%= link_to "Show this kitchen owner", @kitchen_owner %> |
  <%= link_to "Back to kitchen owners", kitchen_owners_path %>
</div>

app/views/kitchen_owners/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Kitchen owners</h1>

<div id="kitchen_owners">
  <% @kitchen_owners.each do |kitchen_owner| %>
    <%= render kitchen_owner %>
    <p>
      <%= link_to "Show this kitchen owner", kitchen_owner %>
    </p>
  <% end %>
</div>

<%= link_to "New kitchen owner", new_kitchen_owner_path %>

app/views/kitchen_owners/new.html.erb
<h1>New kitchen owner</h1>

<%= render "form", kitchen_owner: @kitchen_owner %>

<br>

<div>
  <%= link_to "Back to kitchen owners", kitchen_owners_path %>
</div>

app/views/kitchen_owners/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @kitchen_owner %>

<div>
  <%= link_to "Edit this kitchen owner", edit_kitchen_owner_path(@kitchen_owner) %> |
  <%= link_to "Back to kitchen owners", kitchen_owners_path %>

  <%= button_to "Destroy this kitchen owner", @kitchen_owner, method: :delete %>
</div>