config/routes.rb
Rails.application.routes.draw do
  devise_for :kitchen_owners
  devise_for :cooks
  root "kitchens#index"
  resources :kitchens
  resources :reservations
  resources :cooks
  resources :kitchen_owners
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cook.rb
class Cook < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :reservations
    has_many :kitchen, through: :reservations
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
  before_action :set_cook, only: %i[ show edit update destroy ]

  # GET /cooks or /cooks.json
  def index
    @cooks = Cook.all
  end

  # GET /cooks/1 or /cooks/1.json
  def show
  end

  # GET /cooks/new
  def new
    @cook = Cook.new
  end

  # GET /cooks/1/edit
  def edit
  end

  # POST /cooks or /cooks.json
  def create
    @cook = Cook.new(cook_params)

    respond_to do |format|
      if @cook.save
        format.html { redirect_to cook_url(@cook), notice: "Cook was successfully created." }
        format.json { render :show, status: :created, location: @cook }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cooks/1 or /cooks/1.json
  def update
    respond_to do |format|
      if @cook.update(cook_params)
        format.html { redirect_to cook_url(@cook), notice: "Cook was successfully updated." }
        format.json { render :show, status: :ok, location: @cook }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cooks/1 or /cooks/1.json
  def destroy
    @cook.destroy

    respond_to do |format|
      format.html { redirect_to cooks_url, notice: "Cook was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cook
      @cook = Cook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cook_params
      params.require(:cook).permit(:cook_name, :cook_adress, :cook_number)
    end
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/views/cooks/_cook.html.erb
<div id="<%= dom_id cook %>">
  <p>
    <strong>Nombre:</strong>
    <%= cook.cook_name %>
  </p>

  <p>
    <strong>Domicilio:</strong>
    <%= cook.cook_adress %>
  </p>

  <p>
    <strong>Numero telefonico:</strong>
    <%= cook.cook_number %>
  </p>

</div>

app/views/cooks/_form.html.erb
<%= form_with(model: cook) do |form| %>
  <% if cook.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cook.errors.count, "error") %> prohibited this cook from being saved:</h2>

      <ul>
        <% cook.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cook_name, style: "display: block" %>
    <%= form.text_field :cook_name %>
  </div>

  <div>
    <%= form.label :cook_adress, style: "display: block" %>
    <%= form.text_field :cook_adress %>
  </div>

  <div>
    <%= form.label :cook_number, style: "display: block" %>
    <%= form.number_field :cook_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cooks/edit.html.erb
<h1>Editing cook</h1>

<%= render "form", cook: @cook %>

<br>

<div>
  <%= link_to "Show this cook", @cook %> |
  <%= link_to "Back to cooks", cooks_path %>
</div>

app/views/cooks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cooks</h1>

<div id="cooks">
  <% @cooks.each do |cook| %>
    <%= render cook %>
    <p>
      <%= link_to "Show this cook", cook %>
    </p>
  <% end %>
</div>

<%= link_to "New cook", new_cook_path %>

app/views/cooks/new.html.erb
<h1>Usuario Nuevo</h1>

<%= render "form", cook: @cook %>

<br>

<div>
  <%= link_to "Back to cooks", cooks_path %>
</div>

app/views/cooks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cook %>

<div>
  <%= link_to "Edit this cook", edit_cook_path(@cook) %> |
  <%= link_to "Back to cooks", cooks_path %>

  <%= button_to "Destroy this cook", @cook, method: :delete %>
</div>