config/routes.rb
Rails.application.routes.draw do
  devise_for :kitchen_owners
  devise_for :cooks
  root "kitchens#index"
  resources :kitchens
  resources :reservations
  resources :cooks
  resources :kitchen_owners
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :kitchen
    belongs_to :cook
    has_many :kitchen_owner, through: :kitchens
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    @cooks = Cook.all
    @kitchens = Kitchen.all
  end

  # GET /reservations/1/edit
  def edit
    @cooks = Cook.all
    @kitchens = Kitchen.all
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)


    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        @cooks = Cook.all
        @kitchens = Kitchen.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        @cooks = Cook.all
        @kitchens = Kitchen.all
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:kitchen_id, :cook_id, :working_day, :reserve_date, :reserve_price)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :working_day, style: "display: block" %>
    <%= form.text_field :working_day %>
  </div>

  <div>
    <%= form.label :reserve_date, style: "display: block" %>
    <%= form.date_field :reserve_date %>
  </div>

  <div>
    <%= form.label :reserve_price, style: "display: block" %>
    <%= form.number_field :reserve_price %>
  </div>

  <div>
    <%= form.label :cook_id, style: "display: block" %>
    <%= form.select :cook_id,
    options_from_collection_for_select(@cooks, :id, :cook_name) %>
  </div>

   <div>
    <%= form.label :kitchen_id, style: "display: block" %>
    <%= form.select :kitchen_id,
    options_from_collection_for_select(@kitchens, :id, :kitchen_adress) %>
  </div>

 

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>">
  <p>
    <strong>Working day:</strong>
    <%= reservation.working_day %>
  </p>

  <p>
    <strong>Reserve date:</strong>
    <%= reservation.reserve_date %>
  </p>

  <p>
    <strong>Reserve price:</strong>
    <%= reservation.reserve_price %>
  </p>

</div>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Show this reservation", @reservation %> |
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reservations</h1>

<div id="reservations">
  <% @reservations.each do |reservation| %>
    <%= render reservation %>
    <p>
      <%= link_to "Show this reservation", reservation %>
    </p>
  <% end %>
</div>

<%= link_to "New reservation", new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reservation %>

<div>
  <%= link_to "Edit this reservation", edit_reservation_path(@reservation) %> |
  <%= link_to "Back to reservations", reservations_path %>

  <%= button_to "Destroy this reservation", @reservation, method: :delete %>
</div>