config/routes.rb
Rails.application.routes.draw do
  devise_for :kitchen_owners
  devise_for :cooks
  root "kitchens#index"
  resources :kitchens
  resources :reservations
  resources :cooks
  resources :kitchen_owners
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/kitchen.rb
class Kitchen < ApplicationRecord
    has_many :reservations
    has_many :cook, through: :reservations
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  before_action :set_kitchen, only: %i[ show edit update destroy ]
  before_action :authenticate_kitchen_owner!, except: [:index]

  # GET /kitchens or /kitchens.json
  def index
    @kitchens = Kitchen.all
  end

  # GET /kitchens/1 or /kitchens/1.json
  def show
  end

  # GET /kitchens/new
  def new
    @kitchen = Kitchen.new
  end

  # GET /kitchens/1/edit
  def edit
  end

  # POST /kitchens or /kitchens.json
  def create
    @kitchen = Kitchen.new(kitchen_params)

    respond_to do |format|
      if @kitchen.save
        format.html { redirect_to kitchen_url(@kitchen), notice: "Kitchen was successfully created." }
        format.json { render :show, status: :created, location: @kitchen }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kitchen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kitchens/1 or /kitchens/1.json
  def update
    respond_to do |format|
      if @kitchen.update(kitchen_params)
        format.html { redirect_to kitchen_url(@kitchen), notice: "Kitchen was successfully updated." }
        format.json { render :show, status: :ok, location: @kitchen }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kitchen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitchens/1 or /kitchens/1.json
  def destroy
    @kitchen.destroy

    respond_to do |format|
      format.html { redirect_to kitchens_url, notice: "Kitchen was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitchen
      @kitchen = Kitchen.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kitchen_params
      params.require(:kitchen).permit(:equipment, :services, :kitchen_adress, :kitchen_surface, :kitchen_description)
    end
end

app/helpers/kitchens_helper.rb
module KitchensHelper
end

app/views/kitchens/_form.html.erb
<%= form_with(model: kitchen) do |form| %>
  <% if kitchen.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kitchen.errors.count, "error") %> prohibited this kitchen from being saved:</h2>

      <ul>
        <% kitchen.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :equipment, style: "display: block" %>
    <%= form.text_field :equipment %>
  </div>

  <div>
    <%= form.label :services, style: "display: block" %>
    <%= form.text_field :services %>
  </div>

  <div>
    <%= form.label :kitchen_adress, style: "display: block" %>
    <%= form.text_field :kitchen_adress %>
  </div>

  <div>
    <%= form.label :kitchen_surface, style: "display: block" %>
    <%= form.number_field :kitchen_surface %>
  </div>

  <div>
    <%= form.label :kitchen_description, style: "display: block" %>
    <%= form.text_field :kitchen_description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kitchens/_kitchen.html.erb
<div id="<%= dom_id kitchen %>">
  <p>
    <strong>Equipment:</strong>
    <%= kitchen.equipment %>
  </p>

  <p>
    <strong>Services:</strong>
    <%= kitchen.services %>
  </p>

  <p>
    <strong>Kitchen adress:</strong>
    <%= kitchen.kitchen_adress %>
  </p>

  <p>
    <strong>Kitchen surface:</strong>
    <%= kitchen.kitchen_surface %>
  </p>

  <p>
    <strong>Kitchen description:</strong>
    <%= kitchen.kitchen_description %>
  </p>

</div>

app/views/kitchens/edit.html.erb
<h1>Editing kitchen</h1>

<%= render "form", kitchen: @kitchen %>

<br>

<div>
  <%= link_to "Show this kitchen", @kitchen %> |
  <%= link_to "Back to kitchens", kitchens_path %>
</div>

app/views/kitchens/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Kitchens</h1>

<div id="kitchens">
  <% @kitchens.each do |kitchen| %>
    <%= render kitchen %>
    <p>
      <%= link_to "Show this kitchen", kitchen %>
    </p>
  <% end %>
</div>

<% if kitchen_owner_signed_in? %>
  <%= link_to "New kitchen", new_kitchen_path %>
<% end %>

app/views/kitchens/new.html.erb
<h1>New kitchen</h1>

<%= render "form", kitchen: @kitchen %>

<br>

<div>
  <%= link_to "Back to kitchens", kitchens_path %>
</div>

app/views/kitchens/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @kitchen %>

<div>
  <%= link_to "Edit this kitchen", edit_kitchen_path(@kitchen) %> |
  <%= link_to "Back to kitchens", kitchens_path %>

  <%= button_to "Destroy this kitchen", @kitchen, method: :delete %>
</div>